<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9ecd4d48659b6f799c97f3bb8bb04ee3
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'My_Plugin\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'My_Plugin\\' => 
        array (
            0 => 'C:\\Users\\jeanp\\Local Sites\\chatgpt\\app\\public\\wp-content\\plugins\\my-plugin\\lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9ecd4d48659b6f799c97f3bb8bb04ee3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9ecd4d48659b6f799c97f3bb8bb04ee3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9ecd4d48659b6f799c97f3bb8bb04ee3::$classMap;

        }, null, ClassLoader::class);
    }
}
